package Files;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;

public class Program extends JFrame implements ActionListener {
    public Program() {
        $$$setupUI$$$();
        _openTabs.add("Characters");
        _openTabs.add("Artifacts");
        setContentPane(panel1);
        setTitle("Genshin Domain App!");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(1000, 600);
        setLocationRelativeTo(null);
        setVisible(true);

        //search_cycle();
        /*characterNames.add("Nahida");
        characterNames.add("Xianyun");
        DefaultTableModel dm = new DefaultTableModel(characterNames, 1);
        dm.setValueAt(LabelNahida, 0, 0);
        dm.setValueAt(LabelXianyun, 0, 1);
        CharacterTable = new JTable(dm);*/

    }

    private JPanel panel1;
    private JLabel label1;
    private JTabbedPane tabbedPane1;
    private JPanel panel2;
    private JPanel CharacterTab;
    private JPanel ArtifactsTab;
    private JTextField characterSelectorField;
    private JButton CheckButton;
    private JLabel Result;
    private JPanel selectedCharacterPanel;
    private JTextField textField1;
    private JButton button1;
    private JPanel PreviewTab;
    private Set<String> _openTabs;

    private void createUIComponents() {
        // TODO: place custom component creation code here
        panel1 = new JPanel();
        _openTabs = new HashSet<>();
        CheckButton = new JButton("✓");
        CheckButton.addActionListener(this);
        characterSelectorField = new JTextField();
    }

    public void actionPerformed(ActionEvent e) {
        boolean matched = false;
        selectedCharacterPanel.removeAll();
        String userFieldInput = characterSelectorField.getText().toLowerCase();
        for (int i = 0; i < Data.characters.length; i++) {
            if (Data.characters[i].toLowerCase().contains(userFieldInput)) {
                generateCharacterLabel(Data.characters[i]);
                matched = true;
                //matchedCharacters = matchedCharacters + Data.characters[i] + ", ";
                //Result.setText(Data.characters[i]);
                //return;
            }
        }
        if (!matched) {
            Result.setText("No fighters >:(");
        }

    }

    private void generateCharacterLabel(String characterName) {
        String characterIconPath = "/Files/Images/" + characterName + ".png";
        JButton characterLabel = new JButton();
        Icon characterIcon = new ImageIcon(Objects.requireNonNull(getClass().getResource(characterIconPath)));
        characterLabel.setIcon(characterIcon);
        characterLabel.setText(characterName);
        characterLabel.setVerticalTextPosition(SwingConstants.BOTTOM);
        characterLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        characterLabel.setOpaque(false);
        characterLabel.setBorderPainted(false);
        characterLabel.setContentAreaFilled(false);
        characterLabel.addActionListener(e -> {
            if (_openTabs.add(characterName)) {
                JPanel selectedCharacterTab = new JPanel();
                selectedCharacterTab.setLayout(new GridLayout(2, 3));
                selectedCharacterTab.add(new JLabel(characterIcon));
                selectedCharacterTab.setBackground(new Color(-1));
                selectedCharacterTab.setEnabled(true);
                selectedCharacterTab.setFocusCycleRoot(false);
                selectedCharacterTab.setOpaque(true);
                selectedCharacterTab.setRequestFocusEnabled(true);
                tabbedPane1.addTab(characterName, selectedCharacterTab);
                tabbedPane1.setSelectedComponent(selectedCharacterTab);
            } else {
                tabbedPane1.setSelectedIndex(tabbedPane1.indexOfTab(characterName));
            }
        });
        selectedCharacterPanel.add(characterLabel);
        selectedCharacterPanel.updateUI();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-2702645));
        panel1.setEnabled(true);
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1,
                new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                        GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Source Code Pro Black", Font.BOLD, 20, label1.getFont());
        if (label1Font != null) {
            label1.setFont(label1Font);
        }
        label1.setForeground(new Color(-14940151));
        label1.setText("Genshin Domain Application");
        panel1.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-3689540));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0,
                false));
        tabbedPane1 = new JTabbedPane();
        Font tabbedPane1Font = this.$$$getFont$$$("Source Code Pro Black", Font.BOLD, 20, tabbedPane1.getFont());
        if (tabbedPane1Font != null) {
            tabbedPane1.setFont(tabbedPane1Font);
        }
        tabbedPane1.setTabPlacement(1);
        panel2.add(tabbedPane1,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                        new Dimension(200, 200), null, 0, false));
        CharacterTab = new JPanel();
        CharacterTab.setLayout(new GridBagLayout());
        CharacterTab.setBackground(new Color(-1));
        CharacterTab.setEnabled(true);
        CharacterTab.setFocusCycleRoot(false);
        Font CharacterTabFont = this.$$$getFont$$$(null, -1, -1, CharacterTab.getFont());
        if (CharacterTabFont != null) {
            CharacterTab.setFont(CharacterTabFont);
        }
        CharacterTab.setOpaque(true);
        CharacterTab.setRequestFocusEnabled(true);
        tabbedPane1.addTab("Characters", CharacterTab);
        characterSelectorField.setEnabled(true);
        Font characterSelectorFieldFont =
                this.$$$getFont$$$("Source Code Pro Black", Font.BOLD, 18, characterSelectorField.getFont());
        if (characterSelectorFieldFont != null) {
            characterSelectorField.setFont(characterSelectorFieldFont);
        }
        characterSelectorField.setInheritsPopupMenu(false);
        characterSelectorField.setMaximumSize(new Dimension(240, 33));
        characterSelectorField.setMinimumSize(new Dimension(240, 33));
        characterSelectorField.setPreferredSize(new Dimension(240, 33));
        characterSelectorField.setText("Choose your fighter!");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        gbc.insets = new Insets(0, 250, 0, 0);
        CharacterTab.add(characterSelectorField, gbc);
        CheckButton.setMaximumSize(new Dimension(30, 30));
        CheckButton.setMinimumSize(new Dimension(30, 30));
        CheckButton.setPreferredSize(new Dimension(50, 30));
        CheckButton.setText("✓");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        CharacterTab.add(CheckButton, gbc);
        Result = new JLabel();
        Font ResultFont = this.$$$getFont$$$("Source Code Pro Black", Font.BOLD, 18, Result.getFont());
        if (ResultFont != null) {
            Result.setFont(ResultFont);
        }
        Result.setText("[Result character]");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 10, 0, 0);
        CharacterTab.add(Result, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        CharacterTab.add(panel3, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel3.add(scrollPane1,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null,
                        0, false));
        selectedCharacterPanel = new JPanel();
        selectedCharacterPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        scrollPane1.setViewportView(selectedCharacterPanel);
        ArtifactsTab = new JPanel();
        ArtifactsTab.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        ArtifactsTab.setBackground(new Color(-1));
        tabbedPane1.addTab("Artifacts", ArtifactsTab);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Untitled", panel4);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(textField1, gbc);
        final JLabel label2 = new JLabel();
        label2.setIcon(new ImageIcon(getClass().getResource("/Files/Images/Albedo.png")));
        label2.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setHorizontalAlignment(4);
        label3.setHorizontalTextPosition(4);
        label3.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 0.5;
        gbc.weighty = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(label3, gbc);
        button1 = new JButton();
        button1.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(button1, gbc);
    }

    /** @noinspection ALL */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) {
            return null;
        }
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(),
                size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) :
                new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}

